# -*- coding: utf-8 -*-
"""
YouTube 쿠키 파일 생성 도우미 (v1.0)

사용법:
    1. Chrome 종료
    2. python utils/create_cookies.py
    3. 생성된 data/cookies.txt 확인

또는 수동 생성:
    1. Chrome 확장 "Get cookies.txt LOCALLY" 설치
    2. YouTube에서 쿠키 내보내기
    3. data/cookies.txt에 저장
"""

import os
import sys
import sqlite3
import shutil
from pathlib import Path
from datetime import datetime


def get_chrome_cookies_path() -> Path:
    """Chrome 쿠키 DB 경로 반환"""
    if sys.platform == "win32":
        local_app_data = os.environ.get("LOCALAPPDATA", "")
        paths = [
            Path(local_app_data) / "Google/Chrome/User Data/Default/Network/Cookies",
            Path(local_app_data) / "Google/Chrome/User Data/Default/Cookies",
        ]
        for p in paths:
            if p.exists():
                return p
        return paths[0]  # 기본값
    elif sys.platform == "darwin":
        return Path.home() / "Library/Application Support/Google/Chrome/Default/Cookies"
    else:
        return Path.home() / ".config/google-chrome/Default/Cookies"


def get_edge_cookies_path() -> Path:
    """Edge 쿠키 DB 경로 반환"""
    if sys.platform == "win32":
        local_app_data = os.environ.get("LOCALAPPDATA", "")
        paths = [
            Path(local_app_data) / "Microsoft/Edge/User Data/Default/Network/Cookies",
            Path(local_app_data) / "Microsoft/Edge/User Data/Default/Cookies",
        ]
        for p in paths:
            if p.exists():
                return p
        return paths[0]
    return None


def export_cookies_from_db(db_path: Path, output_path: Path, browser_name: str = "Chrome") -> bool:
    """
    브라우저 쿠키 DB에서 YouTube 쿠키 추출

    Args:
        db_path: 브라우저 쿠키 DB 경로
        output_path: 출력 cookies.txt 경로
        browser_name: 브라우저 이름 (로그용)

    Returns:
        성공 여부
    """

    if not db_path.exists():
        print(f"[{browser_name}] 쿠키 DB를 찾을 수 없습니다: {db_path}")
        return False

    # 임시 복사본 생성 (브라우저가 DB를 잠그고 있을 수 있음)
    temp_db = Path(os.environ.get("TEMP", "/tmp")) / f"{browser_name.lower()}_cookies_copy.db"

    try:
        # SQLite backup API 사용 (읽기 전용 모드)
        src_conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)

        # 복사본 생성
        dst_conn = sqlite3.connect(str(temp_db))
        src_conn.backup(dst_conn)

        src_conn.close()
        dst_conn.close()

        print(f"[{browser_name}] 쿠키 DB 복사 성공")

    except sqlite3.OperationalError as e:
        if "database is locked" in str(e).lower():
            print(f"[{browser_name}] 브라우저가 실행 중입니다. 브라우저를 종료하고 다시 시도하세요.")
        else:
            print(f"[{browser_name}] 쿠키 DB 접근 오류: {e}")
        return False
    except Exception as e:
        print(f"[{browser_name}] 쿠키 DB 복사 실패: {e}")
        return False

    # 쿠키 추출
    try:
        conn = sqlite3.connect(str(temp_db))
        cursor = conn.cursor()

        # YouTube/Google 관련 쿠키 추출
        cursor.execute("""
            SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key LIKE '%youtube.com%'
               OR host_key LIKE '%google.com%'
               OR host_key LIKE '%.youtube.com'
               OR host_key LIKE '%.google.com'
        """)

        cookies = cursor.fetchall()
        conn.close()

        if not cookies:
            print(f"[{browser_name}] YouTube/Google 쿠키를 찾을 수 없습니다.")
            print(f"[{browser_name}] YouTube에 로그인되어 있는지 확인하세요.")
            return False

        # Netscape 형식으로 저장
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f"# Generated by create_cookies.py on {datetime.now().isoformat()}\n")
            f.write(f"# Browser: {browser_name}\n")
            f.write("# This file can be used by yt-dlp with --cookies option\n\n")

            for host, name, value, path, expires, secure, httponly in cookies:
                secure_str = "TRUE" if secure else "FALSE"
                httponly_str = "TRUE" if httponly else "FALSE"

                # Netscape 형식: domain, flag, path, secure, expires, name, value
                f.write(f"{host}\tTRUE\t{path}\t{secure_str}\t{expires}\t{name}\t{value}\n")

        print(f"\n{'='*60}")
        print(f"[{browser_name}] 쿠키 파일 생성 완료!")
        print(f"{'='*60}")
        print(f"   파일: {output_path}")
        print(f"   쿠키 수: {len(cookies)}개")
        print(f"{'='*60}")

        return True

    except Exception as e:
        print(f"[{browser_name}] 쿠키 추출 실패: {e}")
        return False

    finally:
        # 임시 파일 정리
        if temp_db.exists():
            try:
                temp_db.unlink()
            except:
                pass


def main():
    """메인 함수"""

    print()
    print("=" * 60)
    print("       YouTube 쿠키 파일 생성 도우미 v1.0")
    print("=" * 60)
    print()

    # 출력 경로
    project_root = Path(__file__).parent.parent
    output_path = project_root / "data" / "cookies.txt"

    print(f"출력 경로: {output_path}")
    print()

    # 기존 파일 백업
    if output_path.exists():
        backup_path = output_path.with_suffix(f".backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt")
        shutil.copy(output_path, backup_path)
        print(f"기존 파일 백업: {backup_path}")

    # 브라우저 시도 순서: Edge -> Chrome
    success = False

    # Edge 시도
    edge_path = get_edge_cookies_path()
    if edge_path and edge_path.exists():
        print("\n[1/2] Edge 쿠키 추출 시도...")
        if export_cookies_from_db(edge_path, output_path, "Edge"):
            success = True

    # Chrome 시도
    if not success:
        chrome_path = get_chrome_cookies_path()
        print("\n[2/2] Chrome 쿠키 추출 시도...")
        if export_cookies_from_db(chrome_path, output_path, "Chrome"):
            success = True

    if success:
        print()
        print("=" * 60)
        print("  다음 단계:")
        print("=" * 60)
        print("  1. Streamlit 앱 재시작")
        print("  2. 채널 트렌드에서 자막 다운로드 재시도")
        print()
        print("  쿠키 파일 유효 기간: 약 2-4주")
        print("  Rate Limit 발생 시 이 스크립트를 다시 실행하세요.")
        print("=" * 60)
    else:
        print()
        print("=" * 60)
        print("  자동 추출 실패!")
        print("=" * 60)
        print()
        print("  수동 생성 방법:")
        print("  1. Chrome 확장 'Get cookies.txt LOCALLY' 설치")
        print("     https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc")
        print()
        print("  2. YouTube.com 방문 (로그인 상태)")
        print()
        print("  3. 확장 프로그램 클릭 -> Export")
        print()
        print(f"  4. 다운로드된 파일을 여기에 저장:")
        print(f"     {output_path}")
        print("=" * 60)


if __name__ == "__main__":
    main()
